version: "1"
services:
  vassar:
    image: lappsgrid/tomcat7
    user: 'root'
    command: ["/usr/bin/startup"]

registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx
