- hosts: vassar
  tasks:
    - name: Get SET_ENV script
      get_url: url=https://raw.githubusercontent.com/lappsgrid-incubator/docker-vassar/master/setenv.sh dest=/usr/share/tomcat7/bin/setenv.sh
    - name: Get Shutdown script
      get_url: url=https://raw.githubusercontent.com/lappsgrid-incubator/docker-vassar/master/shutdown.sh dest=/usr/bin/shutdown
    - name: Get Tomcat users
      get_url: url=https://raw.githubusercontent.com/lappsgrid-incubator/docker-vassar/master/tomcat-users.xml dest=/usr/share/tomcat7/bin/tomcat-users.xml
    - name: Get MASC Data Source 2.0.0
      get_url: url=http://www.anc.org/downloads/docker/MascDataSource_2.0.0.tgz
    - name: Get MASC Data Source 2.1.0
      get_url: url=http://www.anc.org/downloads/docker/MascDataSource_2.1.0.tgz
    - name: Get MASC Data Source 2.2.0
      get_url: url=http://www.anc.org/downloads/docker/MascDataSource_2.2.0.tgz
      
