version: "1"
services:
  ubuntu:
    image: ubuntu:14.04
    
registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx
