version: "1"
services:
  brandeis:
    image: lappsgrid/tomcat7:1.1.0
    user: 'root'
    command: ["/usr/bin/startup"]

registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx
